###############

GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'MIRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 20
  LR_INITIAL: 2e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 128
  VAL_PS: 192
  RESUME: True
  TRAIN_DIR: './dataset/Blur_var/train' # path to training data
  VAL_DIR: './dataset/Blur_var/val'     # path to validation data
  SAVE_DIR: './checkpoints/Blur'          # path to save models and images
  SAVE_IMAGES: True
  #VAL_AFTER_EVERY: 1
