###############

GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'UIcorrection'
  SESSION: 'FCN'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 100
  LR_INITIAL: 1e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 128
  VAL_PS: 192
  RESUME: False
  TRAIN_DIR: './dataset/UI_var/train' # path to training data
  VAL_DIR: './dataset/UI_var/val'     # path to validation data
  SAVE_DIR: './checkpoints/'          # path to save models and images
  SAVE_IMAGES: FALSE
  #VAL_AFTER_EVERY: 1
