###############
## 
####

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 10
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 10
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 256
  TRAIN_DIR: './Datasets/Noise_var/train' # path to training data
  VAL_DIR: './Datasets/Noise_var/val'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  # SAVE_IMAGES: False
