_BASE_: ../maskformer2_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "D2DiNAT"
  DINAT:
    EMBED_DIM: 192
    DEPTHS: [3, 4, 18, 5]
    NUM_HEADS: [6, 12, 24, 48]
    KERNEL_SIZE: 11
    DILATIONS: [[1, 14, 1], [1, 4, 1, 7], [1, 2, 1, 3, 1, 2, 1, 3, 1, 2, 1, 3, 1, 2, 1, 3, 1, 3], [1, 1, 1, 1, 1]]
    DROP_PATH_RATE: 0.3
  WEIGHTS: "dinat_large_in22k_224.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
SOLVER:
  AMP:
    ENABLED: False
