###############
## 
####

<<<<<<< HEAD
GPU: [0,1]
=======
GPU: [2]
>>>>>>> 5f902b7f6fe54516ec33e5c7c7dc307d60f0e188

VERBOSE: True

MODEL:
  MODE: 'Deblurring'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
<<<<<<< HEAD
  BATCH_SIZE: 8
  NUM_EPOCHS: 10
=======
  BATCH_SIZE: 16
  NUM_EPOCHS: 80
>>>>>>> 5f902b7f6fe54516ec33e5c7c7dc307d60f0e188
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 10
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: './Datasets/Blur_var/train/' # path to training data
  VAL_DIR: './Datasets/Blur_var/val/'    # path to validation data
  SAVE_DIR: './checkpoints'     # path to save models and images
  # SAVE_IMAGES: False
