TRAIN:
  WARMUP_EPOCHS: 5
  EPOCHS: 300
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.05
AUG:
  SSL_AUG: True
MODEL:
  TYPE: WDASSL
  NAME: WDASSL__WDA_tiny__patch4_window7_224__odpr02_tdpr0_cm099_ct02_queue4096_proj2_pred2
  WDA:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
  WDASSL:
    ENCODER: WDA
    ONLINE_DROP_PATH_RATE: 0.2
    TARGET_DROP_PATH_RATE: 0.0
    CONTRAST_MOMENTUM: 0.99
    CONTRAST_TEMPERATURE: 0.2
    CONTRAST_NUM_NEGATIVE: 4096
    PROJ_NUM_LAYERS: 2
    PRED_NUM_LAYERS: 2