# -*- coding: utf-8 -*-
"""IHED.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KqU2WLfGKmhYbMu6j4X4gU56LZK2aM4e
"""

# ! mkdir /content/hyperkvasir/
# #Download the dataset
# ! unzip '/content/drive/MyDrive/Colab Notebooks/PhD-project/Dataset/hyperkvasir.zip' -d "/content/hyperkvasir/"


# ! mkdir /content/kvasir_capsule/
# #Download the dataset
# ! unzip '/content/drive/MyDrive/Colab Notebooks/PhD-project/Dataset/kvasircapsule.zip' -d "/content/kvasir_capsule/"

import numpy as np
import cv2
import csv
import os
import glob
from functools import reduce

stdss = []
orinames = []

file_folder = '/home/nguyentansy/DATA/PhD-work/PhD-project/2021/src/Pre-processing/Isotropic/UnevenIllumination/src/img_ppt/agic/artificial/'


def Average(lst):
    return reduce(lambda a, b: a + b, lst) / len(lst)


# Create a VideoCapture object and read from input file
# If the input is the camera, pass 0 instead of the video file name
clahe = cv2.createCLAHE(tileGridSize=(8, 8))
for file in glob.glob("/home/nguyentansy/DATA/PhD-work/PhD-project/2021/src/Pre-processing/Isotropic/UnevenIllumination/src/img_ppt/agic/artificial/test/test/*v-*.png"):
    # names = os.path.basename(file)+str('.png')
    orinames.append(os.path.basename(file))
    frame = cv2.imread(file, cv2.IMREAD_GRAYSCALE)
    # img = cv2.cvtColor(frame, cv2.COLOR_GRAY2HSV)
    median = cv2.medianBlur(frame, 101)
    ori = median.copy()
    dot = np.mean(ori)
    equ = cv2.equalizeHist(median)
    diff = equ.copy()
    # equ = clahe.apply(frame)
    for i in range(0, equ.shape[0]):
        for j in range(0, equ.shape[1]):
            diff[i][j] = np.abs(
                int(equ[i][j]) - int(ori[i][j])).astype(np.uint8)
    cv2.imwrite(file_folder+"diff" +
                str(os.path.basename(file)), diff)
    mean, std = cv2.meanStdDev(diff, mask=None)
    stdss.append(std/dot)
    print(os.path.basename(file))
    print(mean)
    hist = cv2.calcHist([img],[0],None,[256],[0,256])
#     # cv2.imshow('x', median)
#     # cv2.imshow('eq', res)
#     # plt.hist(img.ravel(), 256, [0, 256])
#     # plt.show()
#     mean, std = cv2.meanStdDev(np.abs(equ-ori), mask=None)
#     dot = np.mean(ori)
#     stds.append(std*dot/255)
#     # Press Q on keyboard to  exit
#     if cv2.waitKey(25) & 0xFF == ord('q'):
#         break

with open('./ihed_test.csv', 'w') as f:
    writer = csv.writer(f, delimiter='\t')
    writer.writerows(zip(orinames, stdss))
